### PR TITLE
proxy support

### PR DESCRIPTION
**Pull request by ekolesnikov**
Hi

The recipe does not work behind proxy server - added proxy support via node attributes.

### CODE REVIEW

**Comment by dhoer** [comment]
Thanks for the PR.  To fix those rubocop issues, run `rubocop -a` and it should fix the offenses.

**Comment by dhoer** [comment]
Take a look at https://github.com/dhoer/chef-chromedriver/pull/7/files#diff-55bf87238c9b8af164c5133a60721f12R16

What do you think of using that?  This would allow consistent management of proxying with Chef.

**Comment by dhoer** [comment]
Or we could do this:
```ruby
ENV['http_proxy'] = 'http://myself:Password1@proxy.example.org:8080'
proxy = ENV['https_proxy'] || ENV['http_proxy'] || false
no_proxy = ENV['no_proxy'] || false
if proxy && (!no_proxy || proxy.host.include?(no_proxy))
  p_addr = URI(proxy).host if proxy
  p_port = URI(proxy).port if proxy

  userinfo = URI(proxy).userinfo if proxy
  p_user = userinfo.split(':')[0] unless userinfo.nil?
  p_pass = userinfo.split(':')[1] unless userinfo.nil?

 response =Net::HTTP.new(uri.host, nil, p_addr, p_port, p_user, p_pass).start { |http| http.get uri.request_uri }
else
  response =Net::HTTP.new(uri.host).start { |http| http.get uri.request_uri }end
end
```
This would be consistent with how chef client handles proxies.

**Comment by dhoer** [comment]
I will accept this PR if you change it to use open (http://ruby-doc.org/stdlib-2.1.0/libdoc/open-uri/rdoc/OpenURI.html) or Chef::HTTP (https://github.com/dhoer/chef-chromedriver/pull/7/files#diff-55bf87238c9b8af164c5133a60721f12R16)

**Comment by dhoer** [comment]
I deleted all of my previous babbling comments.  

Supposably Net::HTTP will automatically create a proxy from the http_proxy environment variable if it is present: http://ruby-doc.org/stdlib-2.3.1/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-Proxies

But it doesn't look like it does based on: http://ruby-doc.org/stdlib-2.3.1/libdoc/net/http/rdoc/Net/HTTP.html#method-c-start.  

I take it you have tried setting ENV['http_proxy'] and it didn't work, correct?

If that is the case, then this is probably the best approach to stay consistent with how Chef and Ruby deal with proxy:

```ruby
# ENV['http_proxy'] = 'http://myself:Password1@proxy.example.org:8080'
proxy = ENV['https_proxy'] || ENV['http_proxy'] || false
no_proxy = ENV['no_proxy'] || false
if proxy && !(no_proxy && proxy.host.include?(no_proxy))
  p_addr = URI(proxy).host if proxy
  p_port = URI(proxy).port if proxy

  userinfo = URI(proxy).userinfo if proxy
  p_user = userinfo.split(':')[0] unless userinfo.nil?
  p_pass = userinfo.split(':')[1] unless userinfo.nil?

  response = Net::HTTP.new(uri.host, nil, p_addr, p_port, p_user, p_pass).start { |http| http.get uri.request_uri }
else
  response = Net::HTTP.new(uri.host).start { |http| http.get uri.request_uri }
end
```

**Comment by dhoer** [comment]
I had a few minutes today to play with this in pry:

```ruby
[1] pry(main)> uri = URI('http://download.sonatype.com/nexus/3/latest-unix.tar.gz')
=> #<URI::HTTP http://download.sonatype.com/nexus/3/latest-unix.tar.gz>
[2] pry(main)> response = Net::HTTP.new(uri.host).start { |http| http.get uri.request_uri }
=> #<Net::HTTPFound 302 Found readbody=true>
[3] pry(main)> response.is_a?(Net::HTTPRedirection)
=> true
[4] pry(main)> ENV['http_proxy'] = 'http://myself:Password1@proxy.example.org:8080'
=> "http://myself:Password1@proxy.example.org:8080"
[5] pry(main)> response2 = Net::HTTP.new(uri.host).start { |http| http.get uri.request_uri }
SocketError: getaddrinfo: nodename nor servname provided, or not known
from /Users/hoerde/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
[6] pry(main)> response2.is_a?(Net::HTTPRedirection)
=> false
```

Based on this, please update this PR to the following and I will accept this:
`response = Net::HTTP.new(uri.host).start { |http| http.get uri.request_uri }`

**Comment by ekolesnikov** [comment]
Hi @dhoer 

Apologies for late reply - lots of things happening.

Setting proxy as an environment variable breaks a lot of other things in Chef - especially when provisioning to AWS, specifically request to retrieve host-metadata (http://169.254.169.254/latest/meta-data). Unfortunately ruby does not allow for "exclude proxy" feature, and it seems adding that on feature level is the only way to make it work.

**Comment by dhoer** [comment]
Will this work? https://docs.chef.io/proxies.html#no-proxy

**Comment by ekolesnikov** [comment]
Hi @dhoer 

Yes, that's exactly what is specified for Chef itself. It seems that the issue is nuanced, complex and quite tricky to reproduce. Here's what is happening:

1. Chef is configured to use our proxy server with exceptions setup - i.e. "remote_file" works perfectly fine as well as "instance_metadata". Exactly as what you have suggested.

2. Unfortunately, this configuration does not propagate down to low-level Ruby code using Net::HTTP directly.

3. Setting up proxy server Ruby-style does fix the issue with low-level Ruby - no additional code required. As per the doc:
https://docs.ruby-lang.org/en/2.0.0/Net/HTTP.html
> **Proxies**
> Net::HTTP will automatically create a proxy from the http_proxy environment variable if it is present. To disable use of http_proxy, pass nil for the proxy address. 

4. However, this also overrides Chef's own proxy settings (because http_proxy env variable works directly with Net::HTTP) including no_proxy statement. This results in AWS instance_metadata call being proxied and returning incorrect result - it returns proxy metadata, not the actual instance's.

Hope this helps.

Many thanks
Egor

**Comment by dhoer** [comment]
Here is a PR that uses Chef::HTTP that inherits Chef's proxy behavior: https://github.com/dhoer/chef-chromedriver/pull/7/files#diff-55bf87238c9b8af164c5133a60721f12R16

Would this address the issue?  I'm trying to figure out if there is a generic solution that can be applied to the dozen other cookbooks I maintain so all of the cookbook have the same behaviors.

**Comment by ekolesnikov** [comment]
Hi @dhoer 

Let me test it in my fork - this seems to be the perfect solution that will resolve the issue in the most appropriate way!

**Comment by dhoer** [comment]
@ekolesnikov Any updates on this?

**Comment by dhoer** [comment]
I would recommend splitting the jetty ssl portion out to a new pr and make it where it can be toggled on or off.

**Comment by dhoer** [comment]
This cookbook has been adopted: https://github.com/criteo-cookbooks/nexus3

**Pull request closed without merging**
