### PR TITLE
New examples for PyPi and RubyGems since 3.0.2 is released

### PR DESCRIPTION
**Pull request by DarthHater**
Adding PyPi and RubyGems examples since 3.0.2 is released and is the new latest for Nexus Repository Manager 3.

### CODE REVIEW

**Comment by DarthHater** [comment]
Appveyor build error seems unrelated to my change.

**Comment by dhoer** [comment]
No problem. Should be fixed now.

**Comment by dhoer** [comment]
btw, thanks for the examples

**Comment by DarthHater** [comment]
No problem!

**Pull request merged**
